### ISSUE TITLE
Repeated options on question 71

### ISSUE THREAD

**Issue by Bernasss12** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#13]
![image](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers/assets/6233500/6106e055-a33f-4f98-81a5-bc29fe929cfc)

**Comment by danieldanielecki** [comment]
Fixed in https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers/commit/8f06747984ced01703baa523c2191920b0ade0ad, @Bernasss12 thanks!
