### ISSUE TITLE
Wrong answers on "Two characteristics the public cloud"

### ISSUE THREAD

**Issue by srv507** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#2]
Hi all,

I think, the answers for the following answer should be:

[What are two characteristics the public cloud? Each correct answer presents a complete solution.](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#what-are-two-characteristics-the-public-cloud-each-correct-answer-presents-a-complete-solution)

![image](https://user-images.githubusercontent.com/118598647/208030441-466bb4d3-ce71-44bb-ad58-d772ed2b1c53.png)

The right answers:
- Metered pricing.
- Self-service management.

However, the answers on the following questinos are right:
[What are two characteristics of the public cloud?](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#what-are-two-characteristics-of-the-public-cloud)

**Comment by danieldanielecki** [comment]
@srv507, please submit PR.

**Comment by danieldanielecki** [comment]
The previous answer was definitely not correct.
It has been fixed in https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers/commit/6c5466ae87409f384aefa304e8052c20ef499467.
