### ISSUE TITLE
Retired answers on "In which Azure support plans can you open a new support request?"

### ISSUE THREAD

**Issue by srv507** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#3]
Hi all,

The answers on the following answer should be retired:
[In which Azure support plans can you open a new support request?](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#in-which-azure-support-plans-can-you-open-a-new-support-request)
![image](https://user-images.githubusercontent.com/118598647/208035481-5294d6ec-d0b5-4e44-9748-4f2487461da8.png)

Because The "Premier support" plan no longer exists, anyhow. See below:

https://azure.microsoft.com/en-us/support/plans/

![image](https://user-images.githubusercontent.com/118598647/208035205-4c70fcc1-e2b9-44f1-85ad-4bf96cb9cc88.png)

And also, the following questions shoudl be reviewed:
[Your company plans to request an architectural review of an Azure environment from Microsoft. The company currently has a Basic support plan. You need to recommend a new support plan for the company. The solution must minimize costs. Which support plan should you recommend?](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#your-company-plans-to-request-an-architectural-review-of-an-azure-environment-from-microsoft-the-company-currently-has-a-basic-support-plan-you-need-to-recommend-a-new-support-plan-for-the-company-the-solution-must-minimize-costs-which-support-plan-should-you-recommend)

**Comment by danieldanielecki** [comment]
@srv507, please submit PR.

**Comment by danieldanielecki** [comment]
Can be closed for now, even if it's retired let's keep it till the new batch question is completely updated.
