### ISSUE TITLE
Azure Site Recovery, fault tolerance or disaster recovery?

### ISSUE THREAD

**Issue by srv507** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#4]
Hi all,

I think the answer for the following answer is "Disaster recovery":
[Azure Site Recovery provides [fault tolerance] for virtual machines.](https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#azure-site-recovery-provides-fault-tolerance-for-virtual-machines)

![image](https://user-images.githubusercontent.com/118598647/208039451-d1cad108-c6bc-46d9-9aeb-fe95a0dab73c.png)

Please refer to:
https://learn.microsoft.com/en-us/azure/site-recovery/site-recovery-overview

![image](https://user-images.githubusercontent.com/118598647/208039702-3467885e-0f62-4b04-b434-bbfa64d997aa.png)

**Comment by danieldanielecki** [comment]
@srv507, please submit PR.
