### ISSUE TITLE
Correction for: Your company has a Software Assurance agreement that includes Microsoft SQL Server licenses. You plan to deploy SQL Server on Azure virtual machines. What should you do to minimize licensing costs for the deployment?

### ISSUE THREAD

**Issue by EChDatAnyl** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#8]
Wrong answer is Deallocate the virtual machines during off hours.

The actual answer is **Use Azure Hybrid Benefit.**

https://learn.microsoft.com/en-us/azure/azure-sql/azure-hybrid-benefit
"Azure Hybrid Benefit allows you to exchange your existing licenses for discounted rates on Azure SQL Database and Azure SQL Managed Instance. You can save up to 30 percent or more on SQL Database and SQL Managed Instance by using your Software Assurance-enabled SQL Server licenses on Azure. The Azure Hybrid Benefit page has a calculator to help determine savings.

Changing to Azure Hybrid Benefit does not require any downtime."

**Comment by danieldanielecki** [comment]
@EChDatAnyl, many thanks for opening the issue :)
You are correct; I fixed it https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers/commit/b3f0a6bb2aaa6e29d153a25f6a70fc52c16515f2.
