### ISSUE TITLE
Correction for What is required to use Azure Cost Management?

### ISSUE THREAD

**Issue by EChDatAnyl** [Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers#9]
Though Enterprise Agreement is one of the correct answers, **pay-as-you-subscription** also works as well.

https://azure.microsoft.com/en-us/products/cost-management

**Comment by danieldanielecki** [comment]
Only `pay-as-you-go subscription is correct` :)

Thank you, fixed in https://github.com/Ditectrev/Microsoft-Azure-AZ-900-Microsoft-Azure-Fundamentals-Exam-Questions-Answers/commit/2fd47f042089a5aa94558741990dfc3bff78de3b
